name: deploy-app
on: push
jobs:
  build-and-deploy: 
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm i
      - name: Build the app
        run: npm run build
